### ISSUE TITLE
How to build python distroless images for `linux/arm/v7` ?

### ISSUE THREAD

**Issue by fabito** [alexdmoss/distroless-python#2]
Hi @alexdmoss,

First of all thanks for sharing this repo, very useful.
I need to built images for `arch=linux/arm/v7`.
I am running containerized workloads on a raspberry pi 4. 

```
 Kernel Version: 5.10.103-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.749GiB
```

Could you point me where to start ?

I checked Google's distroless repo and noticed they have `cc-debian11` for arm. But for some reason they don't publish for `python3-debian11`.

**Comment by reneleonhardt** [comment]
Hello @fabito, you're right, Google doesn't build Distroless arm/v7 images for Java and Python.
I contributed many updates to this image https://gitlab.com/al3xos/distroless-python/-/merge_requests/2 but no one requested arm/v7 you would have to build that Google image yourself ;)
Your Raspbian is very old, 3 years ago it has been renamed to Raspberry Pi OS, and a 64-bit version is available since 1.5 years for the Pi 3B and newer, the easiest way would be to just update your OS to the current version.
https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit
